### ISSUE TITLE
Migrating from ruby to elixir: "connection closed"

### ISSUE THREAD

**Issue by mustela** [nats-io/nats.ex#167]
Hey there! I’m trying to migrate a Ruby project to Elixir, but I’m having issues connecting to the NATS server in Elixir.

In Ruby, I simply have the following code, which works just fine, establishing a connection and allowing interaction with the server:

```
require 'nats/client'
require 'nkeys'

nats = NATS.connect("tls://mynatsserver.com", user_credentials: "/user.creds")
```

In Elixir, I have the following code:

```
settings = %{
  host: "mynatsserver.com",
  auth_required: true,
  nkey_seed: "KEY_FROM_users.creds",
  jwt: "TOKEN__FROM_users.creds"
}

{:ok, gnat} = Gnat.start_link(settings)
```
However, I’m getting the following error:

```
[error] GenServer #PID<0.1968.0> terminating
** (stop) "connection closed"
Last message: {:tcp_closed, #Port<0.68>}
State: %{socket: #Port<0.68>, server_info: %{port: 4222, version: "2.10.18", host: "0.0.0.0", go: "go1.22.5", jetstream: true, headers: true, client_id: 23480, client_ip: "xxx.xxx.xxx.xxx", auth_required: true, nonce: "-WfgHOoqUHuYsRU", server_name: "mynatsserver.com", server_id: "XXXXXXXX", proto: 1, git_commit: "xxxx", tls_required: true, max_payload: 1048576, cluster: "mynatsserver.com", xkey: "XXXXXXX"}, parser: %Gnat.Parsec{partial: nil}, receivers: %{0 => %{monitor_ref: nil, recipient: #PID<0.1968.0>, unsub_after: :infinity}}, request_inbox_prefix: "_INBOX.TohNoPcCHdd2eB+d.", next_sid: 1, request_receivers: %{}, connection_settings: %{port: 4222, host: "mynatsserver.com"", ssl_opts: [], tls: false, auth_required: true, nkey_seed: "SUAXXXXXXXX", jwt: "eyJ0eXAiXXXXXXXXX", inbox_prefix: "_INBOX.", connection_timeout: 3000, no_responders: false, tcp_opts: [:binary]}}
** (EXIT from #PID<0.1880.0>) shell process exited with reason: "connection closed"
```

Enabling ttl does also raise the following error:

```
** (EXIT from #PID<0.1969.0>) shell process exited with reason: an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, {:options, :incompatible, [verify: :verify_peer, cacerts: :undefined]}}
        (gnat 1.8.4) lib/gnat/handshake.ex:28: Gnat.Handshake.perform_handshake/2
        (gnat 1.8.4) lib/gnat.ex:387: Gnat.init/1
        (stdlib 5.2) gen_server.erl:980: :gen_server.init_it/2
        (stdlib 5.2) gen_server.erl:935: :gen_server.init_it/6
        (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

I can’t find the right way to translate that Ruby code into Elixir. Does anyone know what I’m doing wrong?

Thanks!

**Comment by mustela** [comment]
It seems that passing the following connection setting, fixed the issue: 

```
ssl_opts: [
  # Disable all verification
  {:verify, :verify_none}
],
```
